# Unique name for this workflow
name: Salesforce DX CI (scratch org only)

# Definition when the workflow should run
on:
    push:
        branches:
            - master
    pull_request:
        types: [opened, synchronize, reopened]

# Jobs to be executed
jobs:
    formatting-and-linting:
        runs-on: ubuntu-latest
        steps:
            # Checkout the code in the pull request
            - name: 'Checkout source code'
              uses: actions/checkout@v1

            # Cache node_modules to speed up the process
            - name: Restore node_modules cache
              id: cache-npm
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: npm-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      npm-${{ env.cache-name }}-
                      npm-

            # Install npm dependencies for Prettier and Jest
            - name: 'Install npm dependencies'
              if: steps.cache-npm.outputs.cache-hit != 'true'
              run: npm install

            # Prettier formatting
            - name: 'Code formatting'
              run: npm run prettier:verify

            # ESlint
            - name: 'Linting'
              run: npm run lint

            # Unit tests
            - name: 'Unit tests'
              run: npm run test:unit

    scratch-org-test:
        runs-on: ubuntu-latest
        needs: formatting-and-linting
        steps:
            # Checkout the code in the pull request
            - name: 'Checkout source code'
              uses: actions/checkout@v1

            # Store secret for dev hub
            - name: 'Populate auth file with DEVHUB_SFDX_URL secret'
              shell: bash
              run: 'echo ${{ secrets.DEVHUB_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt'

            # Authenticate dev hub
            - name: 'Authenticate Dev Hub'
              uses: forcedotcom/salesforcedx-actions@master
              with:
                  args: 'force:auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a devhub -d'

            # Lint Aura components
            - name: 'Lint Aura components'
              uses: forcedotcom/salesforcedx-actions@master
              with:
                  args: 'force:lightning:lint force-app/main/default/aura --exit'

            # Create scratch org
            - name: 'Create scratch org'
              uses: forcedotcom/salesforcedx-actions@master
              with:
                  args: 'force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1'

            # Deploy source to scratch org
            - name: 'Push source to scratch org'
              uses: forcedotcom/salesforcedx-actions@master
              with:
                  args: 'force:source:push'

            # Run Apex tests in scratch org
            - name: 'Run Apex tests'
              uses: forcedotcom/salesforcedx-actions@master
              with:
                  args: 'force:apex:test:run -c -r human -d ./tests/apex -w 20'

            # Housekeeping
            - name: 'Delete scratch org'
              uses: forcedotcom/salesforcedx-actions@master
              with:
                  args: 'force:org:delete -p -u scratch-org'
